vars:
  - workflows/params.yaml

stages:
  load_moex:
    cmd: python workflows/load_moex_stocks_candles.py
    deps:
    - workflows/load_moex_stocks_candles.py
    params:
    - workflows/params.yaml:
    outs:
    - ${load_moex.paths.output}
  slice_ts:
    cmd: python workflows/slice_moex_trading_ts.py --in_file=${load_moex.paths.output}
    deps:
    - workflows/slice_moex_trading_ts.py
    - ${load_moex.paths.output}
    params:
    - workflows/params.yaml:
    outs:
    - ${slice_ts.paths.output.cluster}
    - ${slice_ts.paths.output.predict}
