vars:
  - workflows/params.yaml

stages:
  load_moex:
    cmd: python workflows/load_moex_stocks_candles.py
    deps:
    - workflows/load_moex_stocks_candles.py
    params:
    - workflows/params.yaml:
    outs:
    - ${load_moex.paths.output}
  slice_ts:
    cmd: python workflows/slice_moex_trading_ts.py --in_file=${load_moex.paths.output}
    deps:
    - workflows/slice_moex_trading_ts.py
    - ${load_moex.paths.output}
    params:
    - workflows/params.yaml:
    outs:
    - ${slice_ts.paths.output.cluster}
    - ${slice_ts.paths.output.predict}
  optuna_optimize:
    cmd: >-
      python workflows/optuna_optimize.py
      --in_file ${slice_ts.paths.output.cluster}
      --model_name ${optuna_optimize.model_name}
      ${optuna_optimize.optimize_range}
      ${optuna_optimize.model_prmt}
      --best_clusters ${optuna_optimize.best_clusters}
      --n_trials ${optuna_optimize.n_trials}
      --par_file ${optuna_optimize.paths.output.parametrs}
      --trials_file ${optuna_optimize.paths.output.trials}
    deps:
    - workflows/optuna_optimize.py
    - ${slice_ts.paths.output.cluster}
    params:
    - workflows/params.yaml:
    outs:
     - ${optuna_optimize.paths.output.parametrs}
